name: Release & Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build library
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release Notes
        id: release-notes
        run: |
          echo "## Release Notes" > release-notes.md
          echo "" >> release-notes.md
          echo "### Features" >> release-notes.md
          echo "- Released version ${{ steps.package-version.outputs.version }}" >> release-notes.md
          echo "" >> release-notes.md
          echo "### Installation" >> release-notes.md
          echo '```bash' >> release-notes.md
          echo "npm install @rabelium/cqrs@${{ steps.package-version.outputs.version }}" >> release-notes.md
          echo '```' >> release-notes.md

      - name: Update Release with Notes
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const release_notes = fs.readFileSync('release-notes.md', 'utf8');
            
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: release_notes
            }); 